export type PresetMode = "long" | "medium" | "short";

export interface ChatPreset {
  mode: PresetMode;
  extra: string;
}

export const PRESET_STORAGE_KEY = "tariq-chat-preset";

export const DEFAULT_PRESET: ChatPreset = {
  mode: "medium",
  extra: "",
};

export const PRESET_MODES: readonly PresetMode[] = ["long", "medium", "short"] as const;

export const PRESET_TEMPLATES: Record<PresetMode, string> = {
  long: "Answer in a long, exact, and comprehensive way. Cite sources when available.",
  medium: "Answer with medium length. No need to cite sources.",
  short: "Answer shortly and quickly. Keep it brief.",
};

const MARKER_RE = /^\[\[PRESET:[^\]]*\]\][\s\S]*?\[\[\/PRESET\]\]\n?/;

export function buildDifyQuery(preset: ChatPreset, userText: string): string {
  const base = PRESET_TEMPLATES[preset.mode];
  const extra = preset.extra.trim();
  const body = extra ? `${base}\n${extra}` : base;
  return `[[PRESET:${preset.mode}]]${body}[[/PRESET]]\n${userText}`;
}

export function stripPresetMarker(query: string): string {
  return query.replace(MARKER_RE, "");
}

// Conversation titles auto-generated by Dify can leak the preset prefix when the
// LLM falls back to a literal slice of the wrapped query. Strip the full marker
// when present, otherwise drop a leading `[[PRESET:...]]` opener that wasn't
// closed (truncated by Dify before the closing `[[/PRESET]]`).
const TRUNCATED_PREFIX_RE = /^\s*\[\[PRESET:[^\]]*\]\][\s\S]*$/;

export function sanitizeConversationTitle(name: string, fallback = "New Chat"): string {
  const stripped = stripPresetMarker(name).trim();
  if (stripped && !TRUNCATED_PREFIX_RE.test(stripped)) return stripped;
  return fallback;
}

export function isPresetMode(value: unknown): value is PresetMode {
  return value === "long" || value === "medium" || value === "short";
}

export function parseStoredPreset(raw: string | null): ChatPreset {
  if (!raw) return DEFAULT_PRESET;
  try {
    const parsed = JSON.parse(raw) as Partial<ChatPreset>;
    const mode = isPresetMode(parsed.mode) ? parsed.mode : DEFAULT_PRESET.mode;
    const extra = typeof parsed.extra === "string" ? parsed.extra : DEFAULT_PRESET.extra;
    return { mode, extra };
  } catch {
    return DEFAULT_PRESET;
  }
}
